### ISSUE TITLE
csv 파일과 db_uploader 파일이 git에 올라오면 안됩니다.

### ISSUE THREAD

**Issue by soheon-lee** [wecode-bootcamp-korea/10-laroche-cream-backend#4]
데이터 업로더와, 데이터 파일이 git에 노출되었어요~ 두 파일은 올라오면 안됩니다.

https://gmlwjd9405.github.io/2018/05/17/git-delete-incorrect-files.html

위 블로그를 참고하여 git에 잘못 올라온 파일을 삭제하는 방법에 대해 공부해주세요 👍

**Comment by hsy118** [comment]
수정 완료했습니다
